<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(AhtolaTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
      <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.11" />
      <PackageReference Include="SourceGear.sqlite3" Version="3.50.4.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ahtola.Data\Ahtola.Data.csproj" />
      <ProjectReference Include="..\Ahtola.Data.Sqlite\Ahtola.Data.Sqlite.csproj" />
    </ItemGroup>

</Project>
