using System.Security.Cryptography;
using AwesomeAssertions;
using Ahtola.Core.Storage;
using Ahtola.Core.Storage.Crypto;
using StorageCipher = Ahtola.Core.Storage.AhtolaEncryptionCipher;

namespace Ahtola.Tests;

/// <summary>
/// Known-answer tests for the managed AEGIS implementations.
/// </summary>
/// <remarks>
/// <para>
/// Every vector is transcribed from the "Test Vectors" appendix of the CFRG
/// specification <c>draft-irtf-cfrg-aegis-aead</c> ("The AEGIS Family of
/// Authenticated Encryption Algorithms", Denis and Lucas, Crypto Forum Research
/// Group). They are independent of Turso and of this port: nothing here was
/// generated by Ahtola, by <c>cargo</c>, or by the <c>aegis</c> Rust crate.
/// </para>
/// <para>
/// Only 128-bit tags are checked because Turso instantiates every AEGIS page
/// cipher as <c>::&lt;16&gt;</c>; Ahtola deliberately produces no 256-bit tags.
/// </para>
/// <para>
/// Each vector runs twice: once through the default policy (AES instructions
/// when the CPU has them) and once pinned to the constant-time software round,
/// which is the path browser-wasm and any CPU without AES instructions takes.
/// </para>
/// </remarks>
public sealed class AegisKnownAnswerTests
{
    private const string Aegis128Key = "10010000000000000000000000000000";
    private const string Aegis128Nonce = "10000200000000000000000000000000";

    private const string Aegis256Key =
        "1001000000000000000000000000000000000000000000000000000000000000";

    private const string Aegis256Nonce =
        "1000020000000000000000000000000000000000000000000000000000000000";

    private const string ParallelKey128 = "000102030405060708090a0b0c0d0e0f";
    private const string ParallelNonce128 = "101112131415161718191a1b1c1d1e1f";

    private const string ParallelKey256 =
        "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";

    private const string ParallelNonce256 =
        "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f";

    private const string ParallelAd = "0102030401020304";

    private const string ParallelMessage =
        "04050607040506070405060704050607040506070405060704050607040506070405060704050607"
        + "04050607040506070405060704050607040506070405060704050607040506070405060704050607"
        + "04050607040506070405060704050607040506070405060704050607040506070405060704050607";

    /// <summary>
    /// The <c>AESRound</c> test vector from the specification appendix. This is
    /// the primitive every AEGIS variant is built from, so pinning it isolates a
    /// bad round function from a bad mode.
    /// </summary>
    [Test]
    public void AesRoundMatchesSpecificationVector()
    {
        var input = System.Runtime.Intrinsics.Vector128.Create<byte>(
            Convert.FromHexString("000102030405060708090a0b0c0d0e0f"));
        var roundKey = System.Runtime.Intrinsics.Vector128.Create<byte>(
            Convert.FromHexString("101112131415161718191a1b1c1d1e1f"));
        var expected = Convert.FromHexString("7a7b4e5638782546a8c0477a3b813f43");

        ToArray(AhtolaAesRound.Encrypt(input, roundKey)).Should().Equal(expected);
        ToArray(AhtolaAesRound.EncryptSoftware(input, roundKey)).Should().Equal(expected);
    }

    /// <summary>The bit-matrix transpose used by the software round is self-inverse and correct.</summary>
    [Test]
    public void SoftwareRoundBitTransposeMatchesNaiveTransposition()
    {
        var random = new Random(20260823);
        Span<byte> buffer = stackalloc byte[8];
        for (var iteration = 0; iteration < 256; iteration++)
        {
            random.NextBytes(buffer);
            var value = System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(buffer);

            ulong expected = 0;
            for (var i = 0; i < 8; i++)
            {
                for (var j = 0; j < 8; j++)
                {
                    var bit = (value >> ((i * 8) + j)) & 1UL;
                    expected |= bit << ((j * 8) + i);
                }
            }

            AhtolaAesRound.Transpose8(value).Should().Be(expected);
            AhtolaAesRound.Transpose8(AhtolaAesRound.Transpose8(value)).Should().Be(value);
        }
    }

    /// <summary>The software round must agree with the hardware round on random inputs.</summary>
    [Test]
    public void SoftwareAesRoundMatchesAcceleratedAesRound()
    {
        if (!AhtolaAesRound.IsHardwareAccelerated)
            Assert.Ignore("This CPU has no AES round instruction; the software round is already the only path.");

        var random = new Random(20260824);
        Span<byte> state = stackalloc byte[16];
        Span<byte> roundKey = stackalloc byte[16];
        for (var iteration = 0; iteration < 512; iteration++)
        {
            random.NextBytes(state);
            random.NextBytes(roundKey);
            var s = System.Runtime.Intrinsics.Vector128.Create<byte>(state);
            var k = System.Runtime.Intrinsics.Vector128.Create<byte>(roundKey);
            ToArray(AhtolaAesRound.EncryptSoftware(s, k)).Should().Equal(ToArray(AhtolaAesRound.Encrypt(s, k)));
        }
    }

    public static IEnumerable<TestCaseData> Aegis128LVectors()
    {
        yield return Vector(
            "AEGIS-128L/1",
            StorageCipher.Aegis128L,
            Aegis128Key,
            Aegis128Nonce,
            associatedData: "",
            message: "00000000000000000000000000000000",
            ciphertext: "c1c0e58bd913006feba00f4b3cc3594e",
            tag: "abe0ece80c24868a226a35d16bdae37a");
        yield return Vector(
            "AEGIS-128L/2",
            StorageCipher.Aegis128L,
            Aegis128Key,
            Aegis128Nonce,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "c2b879a67def9d74e6c14f708bbcc9b4");
        yield return Vector(
            "AEGIS-128L/3",
            StorageCipher.Aegis128L,
            Aegis128Key,
            Aegis128Nonce,
            associatedData: "0001020304050607",
            message: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
            ciphertext: "79d94593d8c2119d7e8fd9b8fc77845c5c077a05b2528b6ac54b563aed8efe84",
            tag: "cc6f3372f6aa1bb82388d695c3962d9a");
        yield return Vector(
            "AEGIS-128L/4",
            StorageCipher.Aegis128L,
            Aegis128Key,
            Aegis128Nonce,
            associatedData: "0001020304050607",
            message: "000102030405060708090a0b0c0d",
            ciphertext: "79d94593d8c2119d7e8fd9b8fc77",
            tag: "5c04b3dba849b2701effbe32c7f0fab7");
        yield return Vector(
            "AEGIS-128L/5",
            StorageCipher.Aegis128L,
            Aegis128Key,
            Aegis128Nonce,
            associatedData:
            "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829",
            message: "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637",
            ciphertext: "b31052ad1cca4e291abcf2df3502e6bdb1bfd6db36798be3607b1f94d34478aa7ede7f7a990fec10",
            tag: "7542a745733014f9474417b337399507");
    }

    public static IEnumerable<TestCaseData> Aegis256Vectors()
    {
        yield return Vector(
            "AEGIS-256/1",
            StorageCipher.Aegis256,
            Aegis256Key,
            Aegis256Nonce,
            associatedData: "",
            message: "00000000000000000000000000000000",
            ciphertext: "754fc3d8c973246dcc6d741412a4b236",
            tag: "3fe91994768b332ed7f570a19ec5896e");
        yield return Vector(
            "AEGIS-256/2",
            StorageCipher.Aegis256,
            Aegis256Key,
            Aegis256Nonce,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "e3def978a0f054afd1e761d7553afba3");
        yield return Vector(
            "AEGIS-256/3",
            StorageCipher.Aegis256,
            Aegis256Key,
            Aegis256Nonce,
            associatedData: "0001020304050607",
            message: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
            ciphertext: "f373079ed84b2709faee373584585d60accd191db310ef5d8b11833df9dec711",
            tag: "8d86f91ee606e9ff26a01b64ccbdd91d");
        yield return Vector(
            "AEGIS-256/4",
            StorageCipher.Aegis256,
            Aegis256Key,
            Aegis256Nonce,
            associatedData: "0001020304050607",
            message: "000102030405060708090a0b0c0d",
            ciphertext: "f373079ed84b2709faee37358458",
            tag: "c60b9c2d33ceb058f96e6dd03c215652");
        yield return Vector(
            "AEGIS-256/5",
            StorageCipher.Aegis256,
            Aegis256Key,
            Aegis256Nonce,
            associatedData:
            "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829",
            message: "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637",
            ciphertext: "57754a7d09963e7c787583a2e7b859bb24fa1e04d49fd550b2511a358e3bca252a9b1b8b30cc4a67",
            tag: "ab8a7d53fd0e98d727accca94925e128");
    }

    public static IEnumerable<TestCaseData> AegisParallelVectors()
    {
        yield return Vector(
            "AEGIS-128X2/1",
            StorageCipher.Aegis128X2,
            ParallelKey128,
            ParallelNonce128,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "63117dc57756e402819a82e13eca8379");
        yield return Vector(
            "AEGIS-128X2/2",
            StorageCipher.Aegis128X2,
            ParallelKey128,
            ParallelNonce128,
            associatedData: ParallelAd,
            message: ParallelMessage,
            ciphertext:
            "5795544301997f93621b278809d6331b3bfa6f18e90db12c4aa35965b5e98c5fc6fb4e54bcb61118"
            + "42c20637252eff747cb3a8f85b37de80919a589fe0f24872bc926360696739e05520647e390989e1"
            + "eb5fd42f99678a0276a498f8c454761c9d6aacb647ad56be62b29c22cd4b5761b38f43d5a5ee062f",
            tag: "1aebc200804f405cab637f2adebb6d77");
        yield return Vector(
            "AEGIS-128X4/1",
            StorageCipher.Aegis128X4,
            ParallelKey128,
            ParallelNonce128,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "5bef762d0947c00455b97bb3af30dfa3");
        yield return Vector(
            "AEGIS-128X4/2",
            StorageCipher.Aegis128X4,
            ParallelKey128,
            ParallelNonce128,
            associatedData: ParallelAd,
            message: ParallelMessage,
            ciphertext:
            "e836118562f4479c9d35c17356a833114c21f9aa39e4dda5e5c87f4152a00fce9a7c38f832eafe8b"
            + "1c12f8a7cf12a81a1ad8a9c24ba9dedfbdaa586ffea67ddc801ea97d9ab4a872f42d0e352e2713da"
            + "cd609f9442c17517c5a29daf3e2a3fac4ff6b1380c4e46df7b086af6ce6bc1ed594b8dd64aed2a7e",
            tag: "0e56ab94e2e85db80f9d54010caabfb4");
        yield return Vector(
            "AEGIS-256X2/1",
            StorageCipher.Aegis256X2,
            ParallelKey256,
            ParallelNonce256,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "62cdbab084c83dacdb945bb446f049c8");
        yield return Vector(
            "AEGIS-256X2/2",
            StorageCipher.Aegis256X2,
            ParallelKey256,
            ParallelNonce256,
            associatedData: ParallelAd,
            message: ParallelMessage,
            ciphertext:
            "72120c2ea8236180d67859001f4729077b7064c414384fe3a7b52f1571f4f8a7d0f01e18db4f3bc0"
            + "adb150702e5d147a8d36522132761b994c1bd395589e2ccf0790dfe2a3d12d61cd666b2859827739"
            + "db4037dd3124c78424459376f6cac08e1a7223a2a43e398ce6385cd654a19f481cba3b8f25910b42",
            tag: "635d391828520bf1512763f0c8f5cdbd");
        yield return Vector(
            "AEGIS-256X4/1",
            StorageCipher.Aegis256X4,
            ParallelKey256,
            ParallelNonce256,
            associatedData: "",
            message: "",
            ciphertext: "",
            tag: "3b7fee6cee7bf17888ad11ed2397beb4");
        yield return Vector(
            "AEGIS-256X4/2",
            StorageCipher.Aegis256X4,
            ParallelKey256,
            ParallelNonce256,
            associatedData: ParallelAd,
            message: ParallelMessage,
            ciphertext:
            "bfc2085b7e8017da99b0b6d646ae4d01f4ba8f2e7dfca1d759ae48a135139b9aaac6b4f5db810d42"
            + "6be1fdaff4e1454153a34b11da78ed7e418ee2ee9853042e95536aecbb694cea1b16a478eb0d4d1b"
            + "f6509b1ce652a45af58e0e46ffccfa2d0426e702391d2ff5813808b81748a490dd656465fed61f09",
            tag: "b63b611b13975e2f3dc3cb6c2397bfcd");
    }

    [TestCaseSource(nameof(Aegis128LVectors))]
    [TestCaseSource(nameof(Aegis256Vectors))]
    [TestCaseSource(nameof(AegisParallelVectors))]
    public void AegisEncryptMatchesSpecificationVector(AegisVector vector)
    {
        foreach (var software in new[] { false, true })
        {
            using var aead = AhtolaAeadFactory.Create(vector.Cipher, vector.Key, software);
            var ciphertext = new byte[vector.Message.Length];
            var tag = new byte[16];
            aead.Encrypt(vector.Nonce, vector.Message, ciphertext, tag, vector.AssociatedData);

            ciphertext.Should().Equal(vector.Ciphertext, $"{vector.Name} ciphertext (software={software})");
            tag.Should().Equal(vector.Tag, $"{vector.Name} tag (software={software})");
        }
    }

    [TestCaseSource(nameof(Aegis128LVectors))]
    [TestCaseSource(nameof(Aegis256Vectors))]
    [TestCaseSource(nameof(AegisParallelVectors))]
    public void AegisDecryptRecoversSpecificationVector(AegisVector vector)
    {
        foreach (var software in new[] { false, true })
        {
            using var aead = AhtolaAeadFactory.Create(vector.Cipher, vector.Key, software);
            var plaintext = new byte[vector.Ciphertext.Length];
            aead.TryDecrypt(vector.Nonce, vector.Ciphertext, vector.Tag, plaintext, vector.AssociatedData)
                .Should().BeTrue($"{vector.Name} must authenticate (software={software})");
            plaintext.Should().Equal(vector.Message, $"{vector.Name} plaintext (software={software})");
        }
    }

    /// <summary>
    /// Specification test vectors 6-9 for AEGIS-128L and AEGIS-256 all demand a
    /// "verification failed" error: swapped key/nonce, a flipped ciphertext byte,
    /// a flipped associated-data byte, and a flipped tag byte.
    /// </summary>
    [TestCase(
        (byte)StorageCipher.Aegis128L,
        "10000200000000000000000000000000",
        "10010000000000000000000000000000",
        "0001020304050607",
        "79d94593d8c2119d7e8fd9b8fc77",
        "5c04b3dba849b2701effbe32c7f0fab7",
        TestName = "Aegis128L_SwappedKeyAndNonce")]
    [TestCase(
        (byte)StorageCipher.Aegis128L,
        Aegis128Key,
        Aegis128Nonce,
        "0001020304050607",
        "79d94593d8c2119d7e8fd9b8fc78",
        "5c04b3dba849b2701effbe32c7f0fab7",
        TestName = "Aegis128L_FlippedCiphertext")]
    [TestCase(
        (byte)StorageCipher.Aegis128L,
        Aegis128Key,
        Aegis128Nonce,
        "0001020304050608",
        "79d94593d8c2119d7e8fd9b8fc77",
        "5c04b3dba849b2701effbe32c7f0fab7",
        TestName = "Aegis128L_FlippedAssociatedData")]
    [TestCase(
        (byte)StorageCipher.Aegis128L,
        Aegis128Key,
        Aegis128Nonce,
        "0001020304050607",
        "79d94593d8c2119d7e8fd9b8fc77",
        "6c04b3dba849b2701effbe32c7f0fab8",
        TestName = "Aegis128L_FlippedTag")]
    [TestCase(
        (byte)StorageCipher.Aegis256,
        "1000020000000000000000000000000000000000000000000000000000000000",
        "1001000000000000000000000000000000000000000000000000000000000000",
        "0001020304050607",
        "f373079ed84b2709faee37358458",
        "c60b9c2d33ceb058f96e6dd03c215652",
        TestName = "Aegis256_SwappedKeyAndNonce")]
    [TestCase(
        (byte)StorageCipher.Aegis256,
        Aegis256Key,
        Aegis256Nonce,
        "0001020304050607",
        "f373079ed84b2709faee37358459",
        "c60b9c2d33ceb058f96e6dd03c215652",
        TestName = "Aegis256_FlippedCiphertext")]
    [TestCase(
        (byte)StorageCipher.Aegis256,
        Aegis256Key,
        Aegis256Nonce,
        "0001020304050608",
        "f373079ed84b2709faee37358458",
        "c60b9c2d33ceb058f96e6dd03c215652",
        TestName = "Aegis256_FlippedAssociatedData")]
    [TestCase(
        (byte)StorageCipher.Aegis256,
        Aegis256Key,
        Aegis256Nonce,
        "0001020304050607",
        "f373079ed84b2709faee37358458",
        "c60b9c2d33ceb058f96e6dd03c215653",
        TestName = "Aegis256_FlippedTag")]
    public void AegisRejectsSpecificationNegativeVector(
        byte cipherId,
        string key,
        string nonce,
        string associatedData,
        string ciphertext,
        string tag)
    {
        var cipher = (StorageCipher)cipherId;
        foreach (var software in new[] { false, true })
        {
            using var aead = AhtolaAeadFactory.Create(cipher, Convert.FromHexString(key), software);
            var ciphertextBytes = Convert.FromHexString(ciphertext);
            var plaintext = new byte[ciphertextBytes.Length];
            plaintext.AsSpan().Fill(0xCC);

            aead.TryDecrypt(
                    Convert.FromHexString(nonce),
                    ciphertextBytes,
                    Convert.FromHexString(tag),
                    plaintext,
                    Convert.FromHexString(associatedData))
                .Should().BeFalse($"the specification requires this vector to fail (software={software})");
            plaintext.Should().OnlyContain(value => value == 0, "unverified plaintext must never be released");
        }
    }

    /// <summary>Ahtola only produces 128-bit AEGIS tags, matching Turso's instantiation.</summary>
    [TestCase(StorageCipher.Aegis256)]
    [TestCase(StorageCipher.Aegis128L)]
    public void AegisRejectsTagSizesOtherThanSixteenBytes(StorageCipher cipher)
    {
        var parameters = AhtolaEncryptedPageFormat.GetParameters(cipher);
        using var aead = AhtolaAeadFactory.Create(cipher, new byte[parameters.KeySize]);
        Assert.Throws<ArgumentException>(
            () => aead.Encrypt(new byte[parameters.NonceSize], [], [], new byte[32], []));
    }

    /// <summary>
    /// AEGIS-128X and AEGIS-256X at degree 1 are defined to equal AEGIS-128L and
    /// AEGIS-256, so a random differential across degrees would be meaningless if
    /// the context separator were applied wrongly. This pins the reduction.
    /// </summary>
    [Test]
    public void ParallelDegreesProduceDistinctCiphertextsFromTheirBaseCipher()
    {
        var message = new byte[512];
        RandomNumberGenerator.Fill(message);

        var aegis128 = EncryptWith(StorageCipher.Aegis128L, ParallelKey128, ParallelNonce128, message);
        var aegis128X2 = EncryptWith(StorageCipher.Aegis128X2, ParallelKey128, ParallelNonce128, message);
        var aegis128X4 = EncryptWith(StorageCipher.Aegis128X4, ParallelKey128, ParallelNonce128, message);
        aegis128.Should().NotEqual(aegis128X2);
        aegis128.Should().NotEqual(aegis128X4);
        aegis128X2.Should().NotEqual(aegis128X4);

        var aegis256 = EncryptWith(StorageCipher.Aegis256, ParallelKey256, ParallelNonce256, message);
        var aegis256X2 = EncryptWith(StorageCipher.Aegis256X2, ParallelKey256, ParallelNonce256, message);
        var aegis256X4 = EncryptWith(StorageCipher.Aegis256X4, ParallelKey256, ParallelNonce256, message);
        aegis256.Should().NotEqual(aegis256X2);
        aegis256.Should().NotEqual(aegis256X4);
        aegis256X2.Should().NotEqual(aegis256X4);
    }

    private static byte[] EncryptWith(
        StorageCipher cipher,
        string key,
        string nonce,
        ReadOnlySpan<byte> message)
    {
        using var aead = AhtolaAeadFactory.Create(cipher, Convert.FromHexString(key));
        var output = new byte[message.Length + 16];
        aead.Encrypt(
            Convert.FromHexString(nonce),
            message,
            output.AsSpan(0, message.Length),
            output.AsSpan(message.Length, 16),
            []);
        return output;
    }

    private static byte[] ToArray(System.Runtime.Intrinsics.Vector128<byte> value)
    {
        var bytes = new byte[16];
        System.Runtime.Intrinsics.Vector128.CopyTo(value, bytes.AsSpan());
        return bytes;
    }

    private static TestCaseData Vector(
        string name,
        StorageCipher cipher,
        string key,
        string nonce,
        string associatedData,
        string message,
        string ciphertext,
        string tag)
        => new TestCaseData(
                new AegisVector(
                    name,
                    cipher,
                    Convert.FromHexString(key),
                    Convert.FromHexString(nonce),
                    Convert.FromHexString(associatedData),
                    Convert.FromHexString(message),
                    Convert.FromHexString(ciphertext),
                    Convert.FromHexString(tag)))
            .SetName($"{{m}}({name})");

    /// <summary>One CFRG AEGIS specification test vector.</summary>
    public sealed record AegisVector(
        string Name,
        StorageCipher Cipher,
        byte[] Key,
        byte[] Nonce,
        byte[] AssociatedData,
        byte[] Message,
        byte[] Ciphertext,
        byte[] Tag);
}
