using System.Security.Cryptography;
using AwesomeAssertions;
using Ahtola.Core.Storage;
using Ahtola.Data.Sqlite.Browser;
using Ahtola.Data.Sqlite.Browser.Storage;
using ProviderCipher = Ahtola.AhtolaEncryptionCipher;
using StorageCipher = Ahtola.Core.Storage.AhtolaEncryptionCipher;

#pragma warning disable CA1416

namespace Ahtola.Tests;

/// <summary>
/// Every browser cipher seam must produce the bytes of the cipher it reports.
/// </summary>
/// <remarks>
/// <para>
/// The browser has two AEAD backends and they are not interchangeable.
/// <see cref="AhtolaBrowserCryptoService"/> is Web Crypto, which implements
/// AES-GCM and nothing else: it imports an <c>AES-GCM</c> JavaScript key and
/// hard-codes AES-GCM's 12-byte nonce and 16-byte tag.
/// <see cref="AhtolaManagedAegisPageCipher"/> is the pure-managed AEGIS core,
/// which uses 16- or 32-byte nonces. A service that accepted an AEGIS cipher id
/// and then imported an AES-GCM key would report one algorithm while producing
/// another's bytes, so the Web Crypto service refuses non-AES ciphers outright.
/// </para>
/// <para>
/// The AEGIS expectations here are the CFRG specification vectors
/// (<c>draft-irtf-cfrg-aegis-aead</c>, "Test Vectors" appendix) reused from
/// <see cref="AegisKnownAnswerTests"/>; nothing below was generated by Ahtola.
/// The AES-GCM expectations are the NIST GCM known answers already pinned by
/// <see cref="AhtolaBrowserCryptoKnownAnswerTests"/>.
/// </para>
/// </remarks>
public sealed class AhtolaBrowserCipherFidelityTests
{
    public static IEnumerable<ProviderCipher> AegisProviderCiphers()
    {
        yield return ProviderCipher.Aegis256;
        yield return ProviderCipher.Aegis256x2;
        yield return ProviderCipher.Aegis256x4;
        yield return ProviderCipher.Aegis128l;
        yield return ProviderCipher.Aegis128x2;
        yield return ProviderCipher.Aegis128x4;
    }

    /// <summary>
    /// The Web Crypto service must never accept an AEGIS cipher id. Before this
    /// gate it imported an AES-GCM key and reported the AEGIS cipher back to the
    /// caller, so <see cref="AhtolaBrowserCryptoService.Cipher"/> disagreed with
    /// the algorithm the key actually ran.
    /// </summary>
    [TestCaseSource(nameof(AegisProviderCiphers))]
    public void WebCryptoServiceRefusesEveryAegisCipher(ProviderCipher cipher)
    {
        var key = new byte[AhtolaBrowserCryptoParameters.GetKeySize(cipher)];

        var failure = Assert.ThrowsAsync<ArgumentOutOfRangeException>(
            async () => await AhtolaBrowserCryptoService.CreateAsync(cipher, key))!;

        failure.ParamName.Should().Be("cipher");
        failure.Message.Should().Contain("AES-GCM only");
        failure.Message.Should().Contain("pure-managed AEGIS page cipher");
    }

    /// <summary>
    /// The refusal is about the algorithm, not the key length: an AEGIS-256 key
    /// is a valid 32-byte AES-256 key, which is exactly why the old behavior
    /// silently succeeded.
    /// </summary>
    [Test]
    public void AegisKeySizesAreValidAesKeySizesSoLengthAloneCannotCatchTheMistake()
    {
        AhtolaBrowserCryptoParameters.GetKeySize(ProviderCipher.Aegis256)
            .Should().Be(AhtolaBrowserCryptoParameters.GetKeySize(ProviderCipher.Aes256Gcm));
        AhtolaBrowserCryptoParameters.GetKeySize(ProviderCipher.Aegis128l)
            .Should().Be(AhtolaBrowserCryptoParameters.GetKeySize(ProviderCipher.Aes128Gcm));
    }

    /// <summary>A cipher with no on-disk id keeps its original diagnosis.</summary>
    [Test]
    public void WebCryptoServiceRefusesCiphersWithNoOnDiskCipherId()
        => Assert.ThrowsAsync<ArgumentOutOfRangeException>(
                async () => await AhtolaBrowserCryptoService.CreateAsync((ProviderCipher)999, new byte[32]))!
            .Message.Should().Contain("ChaCha20-Poly1305 is a Turso Cloud server-side cipher");

    /// <summary>Key-length validation still applies to the ciphers it does accept.</summary>
    [TestCase(ProviderCipher.Aes128Gcm, 32)]
    [TestCase(ProviderCipher.Aes256Gcm, 16)]
    public void WebCryptoServiceStillValidatesAesKeyLength(ProviderCipher cipher, int wrongKeySize)
        => Assert.ThrowsAsync<ArgumentException>(
                async () => await AhtolaBrowserCryptoService.CreateAsync(cipher, new byte[wrongKeySize]))!
            .ParamName.Should().Be("key");

    /// <summary>
    /// The seam the browser actually uses for AEGIS reports the cipher it runs:
    /// each CFRG specification vector must come back byte-for-byte from the
    /// cipher whose <see cref="IAhtolaAsyncPageCipher.Cipher"/> names it.
    /// </summary>
    [TestCaseSource(typeof(AegisKnownAnswerTests), nameof(AegisKnownAnswerTests.Aegis128LVectors))]
    [TestCaseSource(typeof(AegisKnownAnswerTests), nameof(AegisKnownAnswerTests.Aegis256Vectors))]
    [TestCaseSource(typeof(AegisKnownAnswerTests), nameof(AegisKnownAnswerTests.AegisParallelVectors))]
    public async Task ManagedAegisCipherProducesTheVectorOfTheCipherItReports(
        AegisKnownAnswerTests.AegisVector vector)
    {
        await using var cipher = new AhtolaManagedAegisPageCipher(vector.Cipher, vector.Key);

        cipher.Cipher.Should().Be(vector.Cipher);

        var result = await cipher.EncryptAsync(
            vector.Message,
            vector.Nonce,
            vector.AssociatedData,
            default);

        result.Ciphertext.Should().Equal(vector.Ciphertext, $"{vector.Name} ciphertext");
        result.Tag.Should().Equal(vector.Tag, $"{vector.Name} tag");

        var roundTripped = await cipher.DecryptAsync(
            vector.Ciphertext,
            vector.Tag,
            vector.Nonce,
            vector.AssociatedData,
            default);
        roundTripped.Should().Equal(vector.Message, $"{vector.Name} plaintext");
    }

    /// <summary>
    /// The same vector run through an AES-GCM cipher of the same key size must
    /// not reproduce the AEGIS bytes. Without this, "the cipher matches the
    /// bytes" could be satisfied by two backends that happen to agree.
    /// </summary>
    [TestCaseSource(typeof(AegisKnownAnswerTests), nameof(AegisKnownAnswerTests.Aegis128LVectors))]
    [TestCaseSource(typeof(AegisKnownAnswerTests), nameof(AegisKnownAnswerTests.Aegis256Vectors))]
    public void AesGcmCannotReproduceAnAegisVector(AegisKnownAnswerTests.AegisVector vector)
    {
        // AEGIS nonces are 16 or 32 bytes; AES-GCM's are 12. The nonce alone
        // already makes the two frames incompatible, and AES-GCM refuses the
        // AEGIS nonce outright rather than truncating it.
        var aesCipher = vector.Key.Length == 16 ? StorageCipher.Aes128Gcm : StorageCipher.Aes256Gcm;
        AhtolaEncryptedPageFormat.GetParameters(aesCipher).NonceSize
            .Should().NotBe(AhtolaEncryptedPageFormat.GetParameters(vector.Cipher).NonceSize);

        using var aes = new AesGcm(vector.Key, AhtolaBrowserCryptoParameters.AesGcmTagSize);
        var ciphertext = new byte[vector.Message.Length];
        var tag = new byte[AhtolaBrowserCryptoParameters.AesGcmTagSize];
        Assert.Throws<ArgumentException>(
            () => aes.Encrypt(vector.Nonce, vector.Message, ciphertext, tag, vector.AssociatedData));

        // With a legal AES-GCM nonce the output still differs from the vector.
        var truncatedNonce = vector.Nonce.AsSpan(0, AhtolaBrowserCryptoParameters.AesGcmNonceSize).ToArray();
        aes.Encrypt(truncatedNonce, vector.Message, ciphertext, tag, vector.AssociatedData);
        tag.Should().NotEqual(vector.Tag, $"{vector.Name} must not be reproducible with AES-GCM");
        if (vector.Message.Length != 0)
            ciphertext.Should().NotEqual(vector.Ciphertext, $"{vector.Name} ciphertext");
    }

    /// <summary>
    /// The AEGIS seam rejects an AES-GCM-shaped nonce instead of padding or
    /// truncating it, so a caller cannot drive it with AES-GCM framing.
    /// </summary>
    [TestCaseSource(nameof(AegisProviderCiphers))]
    public async Task ManagedAegisCipherRefusesAnAesGcmNonce(ProviderCipher providerCipher)
    {
        var cipher = AhtolaBrowserCryptoParameters.ToStorageCipher(providerCipher);
        var parameters = AhtolaEncryptedPageFormat.GetParameters(cipher);
        await using var pageCipher = new AhtolaManagedAegisPageCipher(cipher, new byte[parameters.KeySize]);

        parameters.NonceSize.Should().NotBe(AhtolaBrowserCryptoParameters.AesGcmNonceSize);
        Assert.ThrowsAsync<ArgumentException>(
            async () => await pageCipher.EncryptAsync(
                new byte[32],
                new byte[AhtolaBrowserCryptoParameters.AesGcmNonceSize],
                default,
                default));
    }

    /// <summary>
    /// The routing that decides which backend serves a cipher is the only thing
    /// keeping the two apart, so it must agree with the nonce widths above.
    /// </summary>
    [Test]
    public void WebCryptoRoutingMatchesTheTwelveByteNonceCiphersExactly()
    {
        foreach (ProviderCipher cipher in Enum.GetValues<ProviderCipher>())
        {
            var storageCipher = AhtolaBrowserCryptoParameters.ToStorageCipher(cipher);
            var usesWebCrypto = AhtolaBrowserCryptoParameters.UsesWebCrypto(cipher);
            var nonceSize = AhtolaEncryptedPageFormat.GetParameters(storageCipher).NonceSize;

            usesWebCrypto.Should().Be(
                nonceSize == AhtolaBrowserCryptoParameters.AesGcmNonceSize,
                $"{cipher} has a {nonceSize}-byte nonce");
        }
    }
}
